# Site Settings
title:              nosnosnos
tagline:            nosnosnosnosnosnosnosnosnosnosnosnosnosnosnos
description:
baseurl:            "/"
url:                "https://nosnosnosnos.github.io"
github:
  url:               #"https://nosnosnosnos.github.io"
author:
  name:              "nosnosnos"
  # email:             ""
  twitter:           "nosnosnos"
  # instagram:         ""
  github:            "nosnosnosnos"
  # facebook:          ""
  # linkedin:          ""
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
# - title: Contact
#   url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
